name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Verificar que GitHub Actions funciona
        run: echo "✅ GitHub Actions está funcionando correctamente."
